// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TTManschatfsSoftware.Data;

#nullable disable

namespace TTManschatfsSoftware.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260610171150_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlayerPlayer", b =>
                {
                    b.Property<Guid>("AvoidWithPlayersId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PreferWithPlayersId")
                        .HasColumnType("uuid");

                    b.HasKey("AvoidWithPlayersId", "PreferWithPlayersId");

                    b.HasIndex("PreferWithPlayersId");

                    b.ToTable("PlayerPlayer");
                });

            modelBuilder.Entity("TTManschatfsSoftware.Domain.Availability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FixtureId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("offen");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FixtureId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PlayerId", "FixtureId")
                        .IsUnique();

                    b.ToTable("Availabilities");
                });

            modelBuilder.Entity("TTManschatfsSoftware.Domain.Block", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PlayerId", "Date");

                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("TTManschatfsSoftware.Domain.Fixture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConfirmedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hall")
                        .HasColumnType("text");

                    b.Property<string>("Opponent")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("offen");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Heim");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Fixtures");
                });

            modelBuilder.Entity("TTManschatfsSoftware.Domain.FixtureDate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FixtureId")
                        .HasColumnType("uuid");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FixtureId");

                    b.ToTable("FixtureDates");
                });

            modelBuilder.Entity("TTManschatfsSoftware.Domain.HallSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Court")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hall")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("Weekday")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("HallSlots");
                });

            modelBuilder.Entity("TTManschatfsSoftware.Domain.LineupEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FixtureId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSubstitute")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FixtureId");

                    b.HasIndex("PlayerId");

                    b.ToTable("LineupEntries");
                });

            modelBuilder.Entity("TTManschatfsSoftware.Domain.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSpvMarked")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Qttr")
                        .HasColumnType("integer");

                    b.Property<DateTime>("QttrDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SeasonNote")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("aktiv");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("TTManschatfsSoftware.Domain.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ExcludeHolidays")
                        .HasColumnType("boolean");

                    b.Property<bool>("ExcludeSchoolBreaks")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("TTManschatfsSoftware.Domain.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("League")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<int>("TargetSize")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("PlayerPlayer", b =>
                {
                    b.HasOne("TTManschatfsSoftware.Domain.Player", null)
                        .WithMany()
                        .HasForeignKey("AvoidWithPlayersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TTManschatfsSoftware.Domain.Player", null)
                        .WithMany()
                        .HasForeignKey("PreferWithPlayersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TTManschatfsSoftware.Domain.Availability", b =>
                {
                    b.HasOne("TTManschatfsSoftware.Domain.Fixture", "Fixture")
                        .WithMany("Availabilities")
                        .HasForeignKey("FixtureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TTManschatfsSoftware.Domain.Player", "Player")
                        .WithMany("Availabilities")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fixture");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("TTManschatfsSoftware.Domain.Block", b =>
                {
                    b.HasOne("TTManschatfsSoftware.Domain.Player", "Player")
                        .WithMany("Blocks")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("TTManschatfsSoftware.Domain.Fixture", b =>
                {
                    b.HasOne("TTManschatfsSoftware.Domain.Team", "Team")
                        .WithMany("Fixtures")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("TTManschatfsSoftware.Domain.FixtureDate", b =>
                {
                    b.HasOne("TTManschatfsSoftware.Domain.Fixture", "Fixture")
                        .WithMany("PreferredDates")
                        .HasForeignKey("FixtureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fixture");
                });

            modelBuilder.Entity("TTManschatfsSoftware.Domain.HallSlot", b =>
                {
                    b.HasOne("TTManschatfsSoftware.Domain.Season", "Season")
                        .WithMany("HallSlots")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("TTManschatfsSoftware.Domain.LineupEntry", b =>
                {
                    b.HasOne("TTManschatfsSoftware.Domain.Fixture", "Fixture")
                        .WithMany("Lineup")
                        .HasForeignKey("FixtureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TTManschatfsSoftware.Domain.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fixture");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("TTManschatfsSoftware.Domain.Player", b =>
                {
                    b.HasOne("TTManschatfsSoftware.Domain.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Team");
                });

            modelBuilder.Entity("TTManschatfsSoftware.Domain.Team", b =>
                {
                    b.HasOne("TTManschatfsSoftware.Domain.Season", "Season")
                        .WithMany("Teams")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Season");
                });

            modelBuilder.Entity("TTManschatfsSoftware.Domain.Fixture", b =>
                {
                    b.Navigation("Availabilities");

                    b.Navigation("Lineup");

                    b.Navigation("PreferredDates");
                });

            modelBuilder.Entity("TTManschatfsSoftware.Domain.Player", b =>
                {
                    b.Navigation("Availabilities");

                    b.Navigation("Blocks");
                });

            modelBuilder.Entity("TTManschatfsSoftware.Domain.Season", b =>
                {
                    b.Navigation("HallSlots");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("TTManschatfsSoftware.Domain.Team", b =>
                {
                    b.Navigation("Fixtures");

                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
